version: "3.7"

x-common-env: &common-env
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"

services:

  postgres:
    image: postgres:10
    container_name: test-postgres
    environment:
      <<: *common-env
    ports:
      - 5432:5432
    volumes:
      - "./scripts:/docker-entrypoint-initdb.d"

  notebook:
    build: .
    container_name: test-notebook
    environment:
      <<: *common-env
    ports: 
      - 8888:8888
    volumes:
      - "./notebooks:/home/jovyan/work"



  